source 'http://rubygems.org'

gem 'rake'
gem 'eventmachine'

gem 'hashie'
gem 'ick'

gem 'ruby-dbus'

group :development do
  gem 'ruby-debug-ide'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
